---
title: Masterclass on Soil Data Assimilation
---

At 24-26 january 2023 [Wageningen Environmental Research](https://www.wur.nl/en/research-results/research-institutes/environmental-research.htm) and
[ISRIC - World Soil Information](https://www.isric.org) has organised a masterclass on Soil Data Assimilation. This masterclass was a follow up of 
the [Training on INSPIRE Good Practices around Soil Data](./edition-2022.qmd) held in april 2022.

## Program (times in CET)

### 24th of january

|  | Building Gaia; Meeting room 2 | Video | 
| --- | --- | --- |
| 10.00 | Introduction to data assimilation (harmonization; extension; codelists) - Paul van Genuchten, Jandirk Bulens | [video](https://wur.yuja.com/V/Video?v=430847&node=1937918&a=83533229&autoplay=1) | 
| 11:00 | INSPIRE Tools - Paul van Genuchten | [video](https://wur.yuja.com/V/Video?v=430878&node=1938063&a=187273784&autoplay=1) |
| 12:00 | Skosmos (code lists) - Paul van Genuchten | [video](https://wur.yuja.com/V/Video?v=430881&node=1938074&a=143339043&autoplay=1) | 
| 14:30 | Soil model in Geopackage - Stefania Morrone  | [video](https://wur.yuja.com/V/Video?v=430869&node=1938006&a=184498297&autoplay=1) | 

 
### 25th of january

| | Lumen 2 meeting room |Video | 
| --- | --- | --- |
| 9.00 | Introduction to View and download services | [video](https://wur.yuja.com/v/ejp-sda-view-download) | 
| 10.00 | Sensorthings API - Kathi Schleidt, Hylke van der Schaaf | [video](https://wur.yuja.com/v/ejp-sda-sta) | 
| 13:45 | WCS - Kathi Schleidt, Peter Baumann | [video](https://wur.yuja.com/v/ejp-sda-wcs) |
| 14:30 | geopython (pygeoapi, pygeometa, pycsw) - Tom Kralidis, Luis de Sousa | [video](https://wur.yuja.com/v/ejp-sda-geopython)  | 


### 26th of january
         
| | Gaia 2 meeting room | Video | 
| --- | --- | ---|
| 9.00 | Introduction to Metadata and discovery | [vido](https://wur.yuja.com/v/ejp-sda-metadata) | 
| 10:00 | deegree webservices intro and Q&A - Torsten Friebe | [video](https://wur.yuja.com/v/ejp-sda-deegree) | 
| 10:30 | MapServer intro and Q&A - Seth G | [video](https://wur.yuja.com/v/ejp-sda-mapserver) | 
| 11:00 | Extending Codelists - Luis de Sousa | [video](https://wur.yuja.com/v/ejp-sda-codelists)  |
| 14.00 | Hale Studio - Kate Lyndegaard |  | 



