---
title: Glossary
summary: 
authors:
    - Paul van Genuchten
    - Luis de Sousa
date: 2023-01-20
---

This page includes terms that we use in our wiki, so that you have a reference for how we’re using them.

*Application programming interface (API)* is a way for two or more computer programs to communicate with each other (source [wikipedia](https://en.wikipedia.org/wiki/API))

*Assimilation* is a catchy term indicating the processes involved to combine multiple datasets with different origin into a common dataset, the term is somewhat similarly used in psychology as `incorporation of new concepts into existing schemes` (source [wikipedia](https://en.wikipedia.org/wiki/Assimilation)). But is not well aligned with its usage in the data science community: ` updating a numerical model with observed data` (source [wikipedia](https://en.wikipedia.org/wiki/Assimilation))

*ATOM* is a standardised interface to exchange news feeds over the internet. It has been adopted by INSPIRE as a basic alternative to download services via WFS or WCS.

*Carbon sequestration* the process of storing carbon (source: [wikipedia](https://en.wikipedia.org/wiki/Carbon_sequestration))

*Carbon stock* the (predicted) amount of carbon stored in a soil

*Catalogue* or *metadata registry* is a central location in an organization where metadata definitions are stored and maintained (source [wikipedia](https://en.wikipedia.org/wiki/Metadata_registry))

*Conceptual model* or *domain model* represents concepts (entities) and relationships between them (source [wikipedia](https://en.wikipedia.org/wiki/Conceptual_model_(computer_science)))

*Content negotiation* refers to mechanisms that make it possible to serve different representations of a resource at the same URI (source [wikipedia](https://en.wikipedia.org/wiki/Content_negotiation))

*Cordis* is the primary source of [results from EU-funded projects](https://cordis.europa.eu/) since 1990

[CSW](https://www.ogc.org/standard/csw) Catalogue Service for the Web

[*Dataverse*](https://dataverse.org/) is open source research data repository software

[*Datacite*](https://datacite.org/) is a non-profit organisation that provides persistent identifiers (DOIs) for research data. It i

[*Datacite metadata schema*](https://schema.datacite.org/) a datamodel for metadata for scientific resources

*Digital exchange of soil-related data (ISO 28258:2013)* presents a conceptual model of a common understanding of what soil profile data are

*Digital soil mapping* is the creation and the population of a geographically referenced soil databases generated at a given resolution by using field and laboratory observation methods coupled with environmental data through quantitative relationships (source: [Wikipedia](https://en.wikipedia.org/wiki/Digital_soil_mapping))

*Discovery service* is a concept from [INSPIRE](https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/discovery) indicating a service type which enables discovery of resources (search and find). Typically implemented as CSW.

*Download service* is a concept from [INSPIRE](https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/download) indicating a service type which enables download of a (subset of a) dataset. Typically implemented as WFS, WCS, SOS or Atom.

[*DOI*](https://www.doi.org/) a digital identifier of an object, any object — physical, digital, or abstract

*Encoding* is the format used to [serialise](https://en.wikipedia.org/wiki/Serialization) a resource to a file, common encodings are xml, json, turtle

[*ESDAC*](https://esdac.jrc.ec.europa.eu/) thematic centre for soil related data in Europe

[*EUSO*](https://joint-research-centre.ec.europa.eu/eu-soil-observatory-euso_en) European Soil Observatory

[GDAL/OGR](https://gdal.org) software package widely used to interact with a variety of spatial data formats

*Geography Markup Language (GML)* is an xml based standardised encoding for spatial data.

[GeoPackage](https://www.ogc.org/standard/geopackage/) a set of conventions for storing spatial data a [SQLite](https://www.sqlite.org/) database

[Geoserver](https://geoserver.org) java based software package providing access to remote data through OGC services

*Global Soil Information System ([GLOSIS](https://www.fao.org/global-soil-partnership/areas-of-work/soil-information-and-data/en/))* is an activity of FAO Global Soil Partnership enabling a federation of soil information systems and interoperable data sets 

*GLOSIS domain model* is an abstract, architectural component that defines how data are organised; it embodies a common understanding of what soil profile data are.

*[GLOSIS Web Ontology](https://github.com/rapw3k/glosis)* is an implementation of the GLOSIS domain model using semantic technology

*[GLOSIS Codelists](https://github.com/rapw3k/glosis/blob/master/glosis_cl.ttl)* is a series of codelists supporting the GLOSIS web ontology. Including the codelists as published in the FAO Guidelines for Soil Description (v2007), soil properties as collected by FAO GfSD and procedures as initally collected by Johan Leenaars.

[Glosolan](https://www.fao.org/global-soil-partnership/glosolan) network to strengthen the capacity of laboratories in soil analysis and to respond to the need for harmonizing soil analytical data

[Humboldt Alignment Editor](https://github.com/halestudio/hale) (HALE) java based desktop software to compose and apply a data transformation to data

*Harmonization* is the process of transforming 2 datasets to a common model, a common projection, usage of common domain values and align their geometries

[ISRIC - World Soil Information](https://www.isric.org/about) independent foundation with a mission to serve the international community as a custodian of global soil information

*JRC* Joint Research Centre. The JRC provides independent, evidence-based science and knowledge, supporting EU policies to positively impact society. Relevant policy areas within JRC are [JRC Soil](https://joint-research-centre.ec.europa.eu/scientific-activities-z/soil_en) and [JRC INSPIRE](https://inspire.ec.europa.eu/whos-who-inspire/57734)

[Mapserver](https://mapserver.org) C based software package providing access to remote data through OGC services

[Observations and Measurements](https://www.ogc.org/standard/om/) (O&M)

[OGC API](https://ogcapi.ogc.org/) building blocks that can be used to assemble novel APIs for web access to geospatial content

*Ontology* a way of showing the properties of a subject area and how they are related, by defining a set of concepts and categories that represent the subject. (source: [wikipedia](https://en.wikipedia.org/wiki/Ontology_(computer_science)))

[QGIS](https://qgis.org) desktop software package to create spatial vizualisations of various types of data

*REA* is the European Research Executive Agency, it's mandate is to manage several EU programmes and support services.

*Relational model* an approach to managing data using a structure and language consistent with first-order predicate logic (source: [wikipedia](https://en.wikipedia.org/wiki/Relational_model))

[Resource Description Framework](https://www.w3.org/RDF/) (RDF) a standard model for data interchange on the Web

Representational state transfer (REST) a set of guidelines for creating stateless, reliable web APIs (source: [wikipedia](https://en.wikipedia.org/wiki/Representational_state_transfer))

[SensorthingsAPI](https://www.ogc.org/standard/sensorthings/) (STA)

[SOS](https://www.ogc.org/standard/sos/) Sensor Observation Service

Soil classification deals with the systematic categorization of soils based on distinguishing characteristics as well as criteria that dictate choices in use (source: [wikipedia](https://en.wikipedia.org/wiki/Soil_classification))

[Soilgrids](https://www.isric.org/explore/soilgrids) a system for global digital soil mapping that uses many profile data and machine learning methods to predict the spatial distribution of soil properties across the globe

*Soil spectroscopy* (source: [soilspectroscopy.org](https://soilspectroscopy.org/) is the measurement of light absorption. The proportion of the incident radiation reflected by soil is sensed through reflectance spectroscopy.

*Unified Modeling Language* (UML) a general-purpose modeling language that is intended to provide a standard way to visualize the design of a system (source: [wikipedia](https://en.wikipedia.org/wiki/Unified_Modeling_Language))

*View service* is a concept from [INSPIRE](https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/view) indicating a service type which presents a (pre)view of a dataset. Typically implemented as WMS or WMTS.

[Wageningen ENvironmental Research](https://www.wur.nl/en/research-results/research-institutes/environmental-research.htm) (WENR) qualified and independent research to the realisation of a high quality and sustainable green living environment

*Webservice* a service offered by a device to another device, communicating with each other via the Internet (source: [wikipedia](https://en.wikipedia.org/wiki/Web_service))

[WOSIS](https://www.isric.org/explore/wosis) aims to serve the user with a selection of standardised and ultimately harmonised soil profile data

[WMS](https://www.ogc.org/standard/wms/) Web Map service

[WFS](https://www.ogc.org/standard/wfs/) Web Feature Service

[WCS](https://www.ogc.org/standard/wcs/) Web Coverage Service

[WMTS](https://www.ogc.org/standard/wmts) Web Map Tile Service

*XML Schema Definition* (XSD) recommendation how to formally describe the elements in an Extensible Markup Language (XML) document (source: [wikipedia](https://en.wikipedia.org/wiki/XML_Schema_(W3C))

